### ISSUE TITLE
please input tomcat version into /data/logs/install_version.txt

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/role_tomcat#1]

**Comment by zengxc-1996** [comment]
TASK [role_tomcat : Install Tomcat] *****************************************************************************************************************************************
fatal: [47.242.54.11]: FAILED! => {"changed": false, "msg": "Failure downloading https://downloads.apache.org/tomcat/tomcat-9/v9.0.45/bin/apache-tomcat-9.0.45.zip, HTTP Error 404: Not Found"}

![image](https://user-images.githubusercontent.com/63622990/118439162-01123280-b718-11eb-8c9e-0c39f96c70da.png)
Please amend for:

https://downloads.apache.org/tomcat/tomcat-9/v9.0.46/bin/apache-tomcat-9.0.46.zip

https://downloads.apache.org/tomcat/tomcat-8/v8.5.66/bin/apache-tomcat-8.5.66.zip

https://downloads.apache.org/tomcat/tomcat-7/v7.0.109/bin/apache-tomcat-7.0.109.zip

**Comment by qiaofeng1227** [comment]
Done

**Comment by tqf6** [comment]
![image](https://user-images.githubusercontent.com/83911329/118639339-5f1f4280-b80a-11eb-904c-c23c2f463f18.png)
![image](https://user-images.githubusercontent.com/83911329/118641731-187f1780-b80d-11eb-8c30-4ce5f6aac787.png)
